version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    resource_class: arm.medium
    steps:
      - checkout
      - run:
          name: "docker login"
          command: "echo $GITLAB_REGISTRY_TOKEN | docker login -u $GITLAB_REGISTRY_USERNAME registry.gitlab.com --password-stdin"
      - run:
          name: "docker build"
          command: "docker build --pull -t registry.gitlab.com/do-copypaste/copypaste_node:latest ."
  
  deploy:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    steps:
      - run:
          name: "deploy over ssh"
          command: |
            ssh ubuntu@$SERVER_HOST_NAME "cd copypaste_node; docker-compose up -d"


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
